"""add_google_oauth

Revision ID: 5c867fdcd77b
Revises: a031264ffd36
Create Date: 2026-04-02 20:22:41.336454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c867fdcd77b'
down_revision: Union[str, Sequence[str], None] = 'a031264ffd36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('fk_contributions_contributor_id'), table_name='contributions')
    op.drop_index(op.f('fk_contributions_reviewer_id'), table_name='contributions')
    op.create_foreign_key(None, 'contributions', 'users', ['reviewer_id'], ['id'])
    op.create_foreign_key(None, 'contributions', 'users', ['contributor_id'], ['id'])
    op.drop_index(op.f('fk_dictionary_examples_entry_id'), table_name='dictionary_examples')
    op.create_foreign_key(None, 'dictionary_examples', 'dictionary_entries', ['entry_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_translation_history_id'), table_name='translation_history')
    op.create_index(op.f('ix_translation_history_id'), 'translation_history', ['id'], unique=False)
    op.create_foreign_key(None, 'translation_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('google_id', sa.String(length=128), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_constraint(None, 'translation_history', type_='foreignkey')
    op.drop_index(op.f('ix_translation_history_id'), table_name='translation_history')
    op.create_index(op.f('ix_translation_history_id'), 'translation_history', ['id'], unique=True)
    op.drop_constraint(None, 'dictionary_examples', type_='foreignkey')
    op.create_index(op.f('fk_dictionary_examples_entry_id'), 'dictionary_examples', ['entry_id'], unique=False)
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.create_index(op.f('fk_contributions_reviewer_id'), 'contributions', ['reviewer_id'], unique=False)
    op.create_index(op.f('fk_contributions_contributor_id'), 'contributions', ['contributor_id'], unique=False)
    # ### end Alembic commands ###
