"""Seed 225 native-speaker verified Bassa expressions."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.database import SessionLocal
from backend.models.dictionary import DictionaryEntry

EXPRESSIONS = [
    ("je dors", "me nanhal"),
    ("tu manges", "u nje"),
    ("il travaille", "a ye bon bolo"),
    ("bonne journee", "kel lam"),
    ("ou vas-tu", "i nke he"),
    ("que dis-tu", "U nkal le ki?"),
    ("ca va bien", "i nke longue"),
    ("ca ne va pas", "i nke be"),
    ("apprends-moi la langue bassa", "niga me hop i bassa"),
    ("je suis originaire de makak", "Me nlol Makak"),
    ("je ne sais pas bien parler", "Me yi be me hop longue"),
    ("mon ami", "Liwanda djem"),
    ("mon frere", "Manke"),
    ("comme c est grand", "Ki i ye keni"),
    ("je suis fauche", "Me ye ntegaga"),
    ("j ai beaucoup d argent", "Me gwe ngandak moni"),
    ("c est beaucoup", "i ye ngandak"),
    ("c est tres beaucoup", "i loha ngandak"),
    ("c est petit", "i ye pera"),
    ("c est gros", "i ye keni"),
    ("c est loin", "i ye haa"),
    ("c est court", "i ye kirik"),
    ("trop", "ngandak"),
    ("c est fini", "A mal"),
    ("ce n est pas fini", "i ye ngi mal"),
    ("un petit garcon", "pera aloga"),
    ("une petite fille", "pera ngonda"),
    ("c est rouge", "i ye koyop"),
    ("c est noir", "i ye langa"),
    ("c est blanc", "i ye puba"),
    ("c est acide", "i mbai"),
    ("c est bon", "i ye lam"),
    ("ce n est pas bon", "i ta be lam"),
    ("c est chaud", "i nlek"),
    ("il fait froid", "lehep li ye"),
    ("il fait chaud", "lek i ye"),
    ("je n ai rien fait", "Me bom be me yom"),
    ("je vais au travail", "Me nke i bolo"),
    ("ne me trompe pas", "U lok ban me"),
    ("ca chatouille", "i nyungana"),
    ("pourquoi pleures-tu", "inyuki u er?"),
    ("pourquoi ris-tu", "inyuki u nol?"),
    ("mes parents", "Bassan bem"),
    ("tes parents", "Bassan bon"),
    ("ses parents", "Bassan be"),
    ("nos parents", "Bassan bes"),
    ("leurs parents", "Bassan bap"),
    ("tu bavardes trop", "U loha hop"),
    ("dis la verite", "kal mbale"),
    ("comment t appelles-tu", "Joy jon le ndje?"),
    ("je t en supplie", "Me nsohe we."),
    ("viens m aider", "Lo hola me."),
    ("ne pleure plus", "U nee a ban."),
    ("je n ai pas d argent", "Me gwe be me moni"),
    ("tu ne vaux rien", "U hola be to yom"),
    ("laisse comme cela", "Mwahak hala"),
    ("ne touche a rien", "U tiss ban to yom"),
    ("viens que je te dise", "Lo me kal we"),
    ("sois le bienvenu", "Malo malam"),
    ("cela sent mauvais", "i numb beba"),
    ("qui cherches-tu", "Dje u yen?"),
    ("que cherches-tu", "ki u yen?"),
    ("les enfants d aujourd hui", "Bongue balen."),
    ("je n en ai pas", "Me gwe be me"),
    ("cela me depasse", "Hala a nlel me"),
    ("rien ne peut me depasser", "Yom i nla be lel me"),
    ("n as-tu pas honte", "U nwo be nyiu?"),
    ("retrouves-moi dehors", "Koba me i mbegre"),
    ("retrouves-moi dedans", "Koba me i kere"),
    ("retourne derriere", "Temb i mbus"),
    ("viens devant", "Lo bissu"),
    ("recule-toi", "Kuhe le"),
    ("donne-moi la voie", "Ti me njel"),
    ("as-tu vu", "U ntehe?"),
    ("tu ne connais rien", "U nyi be to yom!"),
    ("tu n es pas quelqu un", "U ta be mut!"),
    ("je n ai rien compris", "Me nog be me to yom!"),
    ("chercher l argent", "liyen moni"),
    ("faire le commerce", "libon nyiunga"),
    ("ou est-il parti", "A nke he?"),
    ("quand revient-il", "A nlo kegui?"),
    ("causons un peu", "Lo le hanal ndek!"),
    ("c est loin d ici", "i ye ha ni na"),
    ("qui a ferme la porte", "Nje a yip likoga?"),
    ("a qui appartient ceci", "Nje a gwe ini yom?"),
    ("ou habites-tu", "He u yene?"),
    ("ne dis plus rien", "U por a ban to djam"),
    ("j ai mal a la tete", "Ho i nsi me"),
    ("j ai mal au pied", "Mako ma sohe me"),
    ("connais-tu makak", "U yi Makak e?"),
    ("le voici", "Nye nunu"),
    ("le voila", "Nyenuu"),
    ("te voila", "Wenuu"),
    ("me voici", "Me nunu"),
    ("est-ce lui", "Nye nuu?"),
    ("est-ce toi", "Wenuu?"),
    ("c est nous", "Bes ba!"),
    ("ce sont eux", "Bo ba!"),
    ("c est lui", "Nye nu!"),
    ("c est toi", "We nu!"),
    ("c est moi", "Me nu!"),
    ("c est quoi", "Kii?"),
    ("qui est la", "Nje a ye ha?"),
    ("ne m ennuie pas", "U tenga ban me!"),
    ("ne me perds pas mon temps", "U nimis ban me ngera"),
    ("as-tu bien compris", "U nog longue?"),
    ("ecoutez-le", "Hemblana nye!"),
    ("toi aussi", "Yag we"),
    ("assieds-toi", "Yen"),
    ("leve-toi", "Telep"),
    ("j accepte mais", "Me nebe, ndi ..."),
    ("je refuse", "Me ntchel"),
    ("je n ai vu personne", "Me ntes be me to mut"),
    ("je n ai rien vu", "Me ntes be me to yom"),
    ("dis vraiment la verite", "Pot mbale"),
    ("dis seulement la verite", "Pot ndigi mbale"),
    ("je ne veux pas le voir", "Me sombo be me tes nye"),
    ("patience", "Assia!"),
    ("assieds-toi bien", "Tibil yen"),
    ("ne me bouscule pas", "U nyuhe ban me!"),
    ("nous sommes forts", "Di gwe nguy!"),
    ("oui", "ee"),
    ("non", "to"),
    ("viens par ici", "lo hana"),
    ("je n ai meme rien mange", "Me ndje be me to yom!"),
    ("ils ne m ont rien donne", "Ba nti be me to yom"),
    ("quelqu un t a cherche", "nguim mut i nyen we"),
    ("le sais-tu", "u yi hala?"),
    ("je l ai oublie", "Me hoya djo"),
    ("fais attention en marchant", "Yon ngera u nde u nke"),
    ("ferme un peu la bouche", "Yible nyo"),
    ("ne dors plus", "U ke ha ban i lo"),
    ("marche vite", "Ho like"),
    ("marche doucement", "Ke mbehel"),
    ("j ai peur", "Me nkon woni"),
    ("j ai peur de lui", "Me nkon nye"),
    ("n aie peur de rien", "U kon ban yom woni"),
    ("tout le monde", "Bod bobassona"),
    ("comment appelle-t-on ceci", "Lela ba nsebel ini?"),
    ("comment dit-on cela", "Lela ba nkal ini?"),
    ("on ne dit pas cela", "Ba pod be hala"),
    ("ne dis plus ca", "U pod a ban hala!"),
    ("ton habit est sale", "Mbod yon i ye mahindi"),
    ("ton habit est froisse", "Mbod yon i gwe mangorok"),
    ("ton habit est dechire", "Mbod yon i ye mparak"),
    ("parle un peu fort", "Por le ndek makeni"),
    ("il est sorti", "A pam"),
    ("rentres vite", "Ho temb"),
    ("voler n est pas bien", "Wip i ta be longue!"),
    ("c est difficile", "i nlet"),
    ("c est tres facile", "i ntomb ngandak"),
    ("bonjour a vous", "Meyega be Oh!"),
    ("reste tranquille", "Yen mwe"),
    ("comme cela sent bon", "Ki i numb longue!"),
    ("comment", "Lelaa?"),
    ("pourquoi", "inyuki?"),
    ("de quelle facon", "Lelaa?"),
    ("je vais dire", "Ma kal"),
    ("tu aimes beaucoup l argent", "U ngwe moni ngandak"),
    ("l argent c est rien", "Moni a ta be to yom"),
    ("l ami de quelqu un c est quelque chose", "Liwanda li mut li ye nguim djam"),
    ("donne-moi ca", "Ti me ini"),
    ("qui est-tu", "Nje u ye?"),
    ("qui es-tu", "Nje u ye?"),
    ("j ai beaucoup peur", "Me ye me nkon woni"),
    ("ne me trompe plus", "U lok a ban me"),
    ("quittes de la", "Nyori ha!"),
    ("quittes derriere moi", "Nyori me mbous!"),
    ("quittes devant moi", "Nyori me bissu!"),
    ("j aime ta facon de faire", "Me ngwes libonok djon"),
    ("qui a a dire", "Dje a gwe i pot?"),
    ("que lui reclamez-vous", "Ki di bar nye?"),
    ("que me reclamez-vous", "Ki di mbat me?"),
    ("qu oses-tu ainsi", "Kindje U mbon?"),
    ("retrouves-moi au travail", "Koba me i homa bolo"),
    ("rejoins-moi a makak", "Koba me Makak"),
    ("as-tu bien cherche", "U nyen longue?"),
    ("tu n as rien vu", "U ntes be to yom"),
    ("tu ne me depasses en rien", "U lo be me ni to yom"),
    ("que donnes-tu", "Ki U nti?"),
    ("qu est-ce que tu aimes vraiment", "Ki u ngwes mbanga?"),
    ("que puis-je t offrir", "Ki me nla ti we le i nlemel we?"),
    ("on a ferme la voie", "Ba yip njel"),
    ("viens a makak te reposer", "Lo lo noye Makak ndek"),
    ("qui de vous est", "Nje kere nan a ye?"),
    ("qu est-ce qui t ennuie", "Ki i ntengua we?"),
    ("qui est-la dedans", "Nje a ye moukere?"),
    ("qui est-la dehors", "Nje a ye a i mbegre?"),
    ("ne t arrete pas", "U telep ban!"),
    ("tais-toi", "Yip nyo won!"),
    ("je n ai meme pas un rond", "Me gwe be me to dola"),
    ("on fait beaucoup de bruit", "Di nloha i ngandak ninisnga"),
    ("passe par la-bas", "Logne nyo!"),
    ("personne ne t a cherche", "Mud nye ki nye a yen be we"),
    ("qu es-tu en train de dire", "Ki u ye pot?"),
    ("on ne dit pas cela ainsi", "Ba pod be djam li hala"),
    ("parles-tu bien bassa", "U hop longuè i bassa?"),
    ("il est sorti depuis", "A pam koba"),
    ("a combien etes-vous", "Ni ye bes banen?"),
    ("il n est pas ton egal", "A ta be sega yon"),
    ("ce n est meme pas difficile", "i nlet be to ndek"),
    ("il m a insulte", "A nsol me le"),
    ("comme cela sent", "Ki hala a numb!"),
    ("qui attends-tu ici", "Nje u mbem ina?"),
    ("qu attends-tu", "Ki U mbem?"),
    ("qu attends-tu maintenant", "Ki U mbem na a no"),
    ("laisses comme ca", "Mwahak hala"),
    ("les originaires d ici", "Balol ina"),
    ("les camerounais sont de grands travailleurs", "Camerounais ba ye bassal bakeni"),
    ("je n ai rien entendu", "Me nog be to yom"),
    ("personne ne l a jamais ose", "Mud nye ki nye a ye ngi nore djo"),
    ("comment t appelles-tu vraiment", "Joy jon le ndje mbanga?"),
    ("je t en supplie vraiment", "Me nsohe we mbanga"),
    ("s il te plait", "soho"),
    # variantes sans trait d'union (pour le tokeniseur du moteur dictionary)
    ("assieds toi", "Yen"),
    ("leve toi", "Telep"),
    ("assieds toi bien", "Tibil yen"),
    ("ne t arrete pas", "U telep ban!"),
    ("retrouves moi dehors", "Koba me i mbegre"),
    ("retrouves moi dedans", "Koba me i kere"),
]


def main():
    db = SessionLocal()
    existing = {
        e.source_word.lower()
        for e in db.query(DictionaryEntry).filter(DictionaryEntry.source_language == "fr").all()
    }

    added = skipped = 0
    for fr, bas in EXPRESSIONS:
        key = fr.lower().strip()
        if key in existing:
            skipped += 1
            continue
        db.add(DictionaryEntry(
            source_language="fr",
            source_word=key,
            bassa_word=bas,
            category="expression",
            is_verified=True,
            notes="Expression courante (verifie locuteur natif)",
        ))
        existing.add(key)
        added += 1

    db.commit()
    total = db.query(DictionaryEntry).count()
    db.close()
    print(f"{added} expressions ajoutees, {skipped} doublons ignores")
    print(f"Total dictionnaire: {total} entrees")


if __name__ == "__main__":
    main()
